version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - speech_to_text
      - music_generator
    environment:
      - SPEECH_TO_TEXT_URL=http://speech_to_text:8001
      - MUSIC_GENERATOR_URL=http://music_generator:8002
    networks:
      - ai_network

  speech_to_text:
    build:
      context: .
      dockerfile: agents/speech_to_text/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - ai_network

  music_generator:
    build:
      context: .
      dockerfile: agents/music_generator/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./output:/app/output
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge
